### ISSUE TITLE
运行示例报权限错误

### ISSUE THREAD

**Issue by hao3304** [MarkLux/JudgeServer#1]
![image](https://user-images.githubusercontent.com/7592389/34995109-85ce1222-fb10-11e7-8f28-41aef3203cb9.png)

也是ubuntu，root下运行。

**Comment by MarkLux** [comment]
@hao3304 我也发现这个问题了，我在osx上做的开发，docker里ld行为跟服务器上不太一致，正在修复，建议先回滚之前的版本继续使用（最近加班多，不好意思）

**Comment by MarkLux** [comment]
@hao3304 最新版本已修复。
